# action.yml
name: 'Qovery deploy'
description: 'Deploy on your Qovery projects'
author: Qovery <support@qovery.com>

branding:
  icon: "upload-cloud"
  color: "purple"

inputs:
  qovery-api-token:
    description: 'Qovery API token'
    required: true
  qovery-organization-id:
    description: 'Qovery organization ID'
    required: true
  qovery-environment-id:
    description: 'Qovery environment ID'
    required: true
  qovery-application-ids:
    description: 'Qovery applications IDS'
    required: false
  qovery-database-id:
    description: 'Qovery database ID'
    required: false
outputs:
  environment-state:
    description: 'Environment state on which app has been deployed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --org-id=${{ inputs.qovery-organization-id }}
    - --env-id=${{ inputs.qovery-environment-id }}
    - --app-ids=${{ inputs.qovery-application-ids }}
    - --app-commit-id=${{ inputs.qovery-application-ids }}
    - --db-id=${{ inputs.qovery-database-id }}
    - --api-token=${{ inputs.qovery-api-token }}
