# action.yml
name: 'Qovery deploy'
description: 'Deploy on your Qovery projects'
author: Qovery <support@qovery.com>

branding:
  icon: "upload-cloud"
  color: "purple"

inputs:
  qovery-organization-id:
    description: 'Qovery organization ID'
    required: true
  qovery-environment-id:
    description: 'Qovery environment ID'
    required: true
  qovery-application-ids:
    description: 'Qovery applications IDS'
    required: true
  qovery-api-token:
    description: 'Qovery API token'
    required: true
outputs:
  environment-state:
    description: 'Environment state on which app has been deployed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.qovery-organization-id }}
    - ${{ inputs.qovery-environment-id }}
    - ${{ inputs.qovery-application-ids }}
    - ${{ inputs.qovery-api-token }}
